[package]
name = "rms"
version = "0.1.0"
authors = ["Lewis Diamond <lewis@jogogo.co>"]
edition = "2018"

[dependencies]
mailparse = "0.6.4"
maildir = "0.1.2"
rayon = "1.0.3"
tantivy = "0.8.1"
tempdir = "0.3.7"
serde_json = "1.0.33"
structopt = "0.2.14"
shellexpand = "1.0"
log = "0.4"
pretty_env_logger = "0.3"
