[package]
name = "rms"
version = "0.1.0"
authors = ["Lewis Diamond <lewis@jogogo.co>"]
edition = "2018"

[dependencies]
#maildir = { git = "https://github.com/lewisdiamond/maildir.git" }
maildir = { path = "/home/ldiamond/dev/maildir/" }
#html2text = "0.1.8"
html2text = { git = "https://github.com/lewisdiamond/rust-html2text.git"}
mailparse = "0.6.5"
rayon = "1.0.3"
tantivy = "0.8.1"
tempdir = "0.3.7"
serde_json = "1.0.33"
structopt = "0.2.14"
shellexpand = "1.0"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] } 
pretty_env_logger = "0.3"
pbr = "1.0.1"
num_cpus = "1.9.0"
sys-info = "0.5.6"
tui = "0.4.0"
termion = "1.5.1"
chrono = "0.4.6"
sha2 = "0.8.0"
html5ever = "*"
rocksdb = "0.12.0"
serde = { version = "1.0.89", features = ["derive"]}
