[package]
name = "rms"
version = "0.1.0"
authors = ["Lewis Diamond <lewis@jogogo.co>"]
edition = "2018"

[dependencies]
#maildir = { git = "https://github.com/lewisdiamond/maildir.git" }
maildir = { path = "/home/ldiamond/dev/maildir/" }
html2text = "0.1.13"
#html2text = { git = "https://github.com/lewisdiamond/rust-html2text.git"}
mailparse = "0.13.0"
rayon = "1.3.1"
tantivy = "0.12.0"
tempdir = "0.3.7"
serde_json = "1.0.57"
serde = { version = "1.0.114", features = ["derive"] }
structopt = "0.3.15"
shellexpand = "2.0.0"
log = { version = "0.4.11", features = ["max_level_debug", "release_max_level_warn"] } 
pretty_env_logger = "0.4.0"
pbr = "1.0.3"
num_cpus = "1.13.0"
sys-info = "0.7.0"
tui = "0.10.0"
termion = "1.5.5"
chrono = "0.4.13"
sha2 = "0.9.1"
html5ever = "0.25.1"
rocksdb = { path = "../rust-rocksdb/" }
jemallocator = "0.3.2"
#maildir = "0.4.2"
select = "0.5.0"

[dev-dependencies]
rand = "0.7.3"
